export interface CultureEvent {
  id: string;
  title: string;
  devanagari: string;
  category: string;
  denomination: string;
  teaser: string;
  description: string;
  date: string;
  venue: string;
  format: string;
  rulesLink?: string;
  placeholderImg: string;
  registrationFee: string;
  prizePool: string;
  teamSize: string;
  participationType: string;
  eligibility: string;
  registrationDeadline: string;
  _note?: string; // Internal note for conflicts/ambiguities
}

const IMG = {
  dancer: '/assets/reference/cultural/ref_c-4.jpg',
  stencil: '/assets/reference/cultural/ref_c-16.jpg',
  performer: '/assets/reference/cultural/ref_c-17.jpg',
  chaiwala: '/assets/reference/cultural/ref_c-2.jpg',
} as const;

export const cultureData: CultureEvent[] = [
  {
    id: 'solo-classical-dance',
    title: 'Solo Classical Dance',
    devanagari: 'नृत्यांजलि',
    category: 'Dance',
    denomination: '₹25',
    teaser: 'Tradition in Every Step, Grace in Every Move.',
    description: 'A solo classical dance showcase where mudra, abhinaya, and rhythmic technique come together to express devotion, elegance, and discipline rooted in Indian classical tradition.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.dancer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹10,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'group-classical-dance',
    title: 'Group Classical Dance',
    devanagari: 'नृत्य समूह',
    category: 'Dance',
    denomination: '₹30',
    teaser: 'Synchrony Rooted in Tradition.',
    description: 'A group classical dance competition where teams create harmony through intricate rhythm, grace, and devotion, weaving stories through collective artistry.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Group',
    rulesLink: '#',
    placeholderImg: IMG.dancer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹20,000',
    teamSize: 'Not specified',
    participationType: 'Team',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'solo-western-dance',
    title: 'Solo Western Dance',
    devanagari: 'पश्चिमी नृत्य',
    category: 'Dance',
    denomination: '₹20',
    teaser: 'One Stage, One Performer, Unlimited Expression.',
    description: 'A solo western-style dance event (hip-hop, jazz, or freestyle) where the performer owns the spotlight with individual creativity, energy, and rhythm.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.stencil,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹10,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'group-western-dance',
    title: 'Group Western Dance',
    devanagari: 'समूह पश्चिमी नृत्य',
    category: 'Dance',
    denomination: '₹30',
    teaser: 'Where Teams Create Magic in Motion.',
    description: 'A team-based western dance battle built on synchronized energy and choreography, judged on formations, coordination, charisma, and overall stage presence.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Group',
    rulesLink: '#',
    placeholderImg: IMG.stencil,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹20,000',
    teamSize: 'Not specified',
    participationType: 'Team',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'street-dance',
    title: 'Street Dance',
    devanagari: 'सड़क नृत्य',
    category: 'Dance',
    denomination: '₹15',
    teaser: 'Freestyle battles where the open cypher crowns a street champion.',
    description: 'An open freestyle dance battle — popping, breaking, or any street style — performed in a cypher setting where crowd energy helps crown the winner.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.stencil,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000 (Winner takes all)',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'battle-of-bands',
    title: 'Battle of Bands',
    devanagari: 'बैंडों का युद्ध',
    category: 'Music',
    denomination: '₹35',
    teaser: 'A cutthroat live-music showdown between bands of every genre.',
    description: 'Live bands compete head-to-head with guitar solos and drum performances, testing talent, creativity, and stage performance skills across genres.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Band',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹40,000',
    teamSize: 'Not specified',
    participationType: 'Team (band)',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'solo-instrumental',
    title: 'Solo Instrumental',
    devanagari: 'वादन',
    category: 'Music',
    denomination: '₹20',
    teaser: 'An unforgettable night of solo instrumental mastery.',
    description: 'A solo instrumental competition celebrating musical artistry, from soulful melodies to high-energy rhythms.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹7,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'solo-singing',
    title: 'Solo Singing',
    devanagari: 'गायन',
    category: 'Music',
    denomination: '₹20',
    teaser: 'Open your heart and let your voice take the stage.',
    description: 'A solo vocal competition ("Melodies") where participants express emotion through singing and let their voice capture the stage.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹7,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'rap-battle',
    title: 'Rap Battle',
    devanagari: 'रैप बैटल',
    category: 'Music',
    denomination: '₹15',
    teaser: 'Bars, wit, and flow collide in the open cipher.',
    description: 'An open-mic rap battle where participants bring punchlines, flow, and wit to out-rhyme the competition and win over the crowd.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000 (Winner takes all)',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'stage-play',
    title: 'Stage Play',
    devanagari: 'रंगमंच',
    category: 'Drama',
    denomination: '₹30',
    teaser: 'A night of captivating stories and powerful group performances.',
    description: 'A group drama showcase bringing together raw emotion and top-tier acting, with talented performers creating an unforgettable evening on stage.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Group',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹23,000',
    teamSize: 'Not specified',
    participationType: 'Team',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'mono-acting',
    title: 'Mono Acting',
    devanagari: 'एकल अभिनय',
    category: 'Drama',
    denomination: '₹15',
    teaser: 'A solo actor bares their raw self to the audience\'s scrutiny.',
    description: 'A solo acting event that strips away performed social roles, exposing the actor\'s intellect, poise, and voice in a moment of emotional revelation.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Solo',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹7,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'mock-trading',
    title: 'Mock Trading',
    devanagari: 'मॉक ट्रेडिंग',
    category: 'Business',
    denomination: '₹10',
    teaser: 'A virtual trading arena to crown "The Big Bull."',
    description: 'A mock stock-trading competition where participants battle in a virtual arena to compete for the title of "The Big Bull."',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Simulation',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹6,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'shark-tank',
    title: 'Shark Tank',
    devanagari: 'शार्क टैंक',
    category: 'Business',
    denomination: '₹25',
    teaser: 'Student entrepreneurs pitch bold ideas to a panel of investors.',
    description: 'An entrepreneurial pitch competition where aspiring studentpreneurs present innovative business ideas to a panel of experienced investors ("Sharks") — a platform where innovation meets investment.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Pitch',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹10,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'debate',
    title: 'Debate',
    devanagari: 'वाद-विवाद',
    category: 'Business',
    denomination: '₹10',
    teaser: 'A fast-paced clash of words where the sharpest argument wins.',
    description: 'A fast-paced debate competition where words and wit determine the winner, favoring the sharpest minds and strongest arguments.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Debate',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹6,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'cricket-auction',
    title: 'Cricket Auction',
    devanagari: 'क्रिकेट नीलामी',
    category: 'Business',
    denomination: '₹20',
    teaser: 'An IPL-style auction showdown full of strategy and unexpected twists.',
    description: 'A mock cricket-auction competition where teams unite in a fierce battle of strategy and skill, recreating the thrill of an IPL-style auction with unexpected twists and turns.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Auction',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹14,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'fashion-show',
    title: 'Fashion Show',
    devanagari: 'फैशन शो',
    category: 'Lifestyle',
    denomination: '₹40',
    teaser: 'The Runway Revolution.',
    description: 'Falak\'s fashion show celebrating bold styles, dazzling confidence, and creative themes on the runway — an experience of artistry, attitude, and flair.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Showcase',
    rulesLink: '#',
    placeholderImg: IMG.stencil,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹20,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'treasure-hunt',
    title: 'Treasure Hunt',
    devanagari: 'खजाने की खोज',
    category: 'Lifestyle',
    denomination: '₹15',
    teaser: 'Clues, Chaos, and the Chase for Glory.',
    description: 'An adventure blending puzzles, riddles, and thrill, where teams gather to crack codes and race against time to uncover hidden secrets across campus.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Hunt',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹10,000',
    teamSize: 'Not specified',
    participationType: 'Team',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'what-the-falak',
    title: 'What The Falak?',
    devanagari: 'व्हाट द फलक?',
    category: 'Lifestyle',
    denomination: '₹20',
    teaser: 'Unfiltered Charisma, Zero Limits, Pure Personality.',
    description: 'A non-traditional talent show where participants showcase quirks, wild stories, quick wit, and unapologetic personality to charm a mystery panel and win over the crowd.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Talent Show',
    rulesLink: '#',
    placeholderImg: IMG.performer,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹12,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'short-filmmaking',
    title: 'Short Filmmaking',
    devanagari: 'लघु फिल्म निर्माण',
    category: 'Creative',
    denomination: '₹25',
    teaser: 'Filmmakers bring their vision to life for top honors.',
    description: 'A short-film competition at MAHE Bengaluru inviting filmmakers to showcase creativity, with awards for the top three entries plus two special mentions.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Submission',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹8,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'ad-designing',
    title: 'Ad Designing',
    devanagari: 'विज्ञापन डिजाइनिंग',
    category: 'Creative',
    denomination: '₹15',
    teaser: 'A creative ad-design battle blending video, marketing, and wit.',
    description: 'A creative ad-design competition where participants craft innovative video ads, competing for prizes while developing skills in video production, creativity, and marketing.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Submission',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹8,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'reel-making',
    title: 'Reel Making',
    devanagari: 'रील मेकिंग',
    category: 'Creative',
    denomination: '₹10',
    teaser: 'Turn the fest\'s chaos into the season\'s most viral reel.',
    description: 'Participants capture the ultimate festival energy on their phones around campus, using transitions, aesthetics, or comedy to flex storytelling skills and make the most viral reel of the season.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Submission',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'photography',
    title: 'Photography',
    devanagari: 'फोटोग्राफी',
    category: 'Creative',
    denomination: '₹10',
    teaser: 'Capture unique moments and tell your story through the lens.',
    description: 'A photography event ("Spectra") open to all skill levels, inviting participants to capture unique moments and tell their story through images, celebrating diverse perspectives.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Submission',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹6,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Open to all skill levels',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'pop-culture-quiz',
    title: 'Pop Culture Quiz',
    devanagari: 'पॉप कल्चर क्विज',
    category: 'Quiz',
    denomination: '₹10',
    teaser: 'Test your knowledge of pop culture, past and present.',
    description: 'A quiz testing knowledge of pop culture from past to present — viral trends, social media hits, blockbuster films, and celebrity news.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Quiz',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'general-quiz',
    title: 'General Quiz',
    devanagari: 'सामान्य ज्ञान क्विज',
    category: 'Quiz',
    denomination: '₹10',
    teaser: 'A trivia extravaganza across general knowledge domains.',
    description: 'A general-knowledge quiz extravaganza where teams show off their trivia skills across various domains, competing for prizes.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Quiz',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000',
    teamSize: 'Not specified',
    participationType: 'Team',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'ea-sports-fc-25',
    title: 'EA Sports FC 25',
    devanagari: 'ईए स्पोर्ट्स एफसी 25',
    category: 'Esports',
    denomination: '₹15',
    teaser: 'Head-to-head football gaming knockout for ultimate glory.',
    description: 'An EA Sports FC 25 tournament with a knockout format, letting players showcase football-gaming skills head-to-head for exciting prizes.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Knockout',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000',
    teamSize: 'Individual',
    participationType: 'Individual (head-to-head)',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'clash-royale',
    title: 'Clash Royale',
    devanagari: 'क्लैश रोयाल',
    category: 'Esports',
    denomination: '₹15',
    teaser: 'Real-time strategy battles to dominate the arena.',
    description: 'A real-time head-to-head battle game where players build a battle deck of unique cards and outsmart opponents in the Arena.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Head-to-head',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹5,000',
    teamSize: 'Individual',
    participationType: 'Individual (head-to-head)',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'cod-mobile',
    title: 'COD Mobile',
    devanagari: 'कॉल ऑफ ड्यूटी मोबाइल',
    category: 'Esports',
    denomination: '₹20',
    teaser: 'Prove your FPS skills and climb to the summit.',
    description: 'A Call of Duty Mobile tournament open to veterans and underdogs alike, competing for a share of the prize pool.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Tournament',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹10,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'bgmi',
    title: 'BGMI',
    devanagari: 'बीजीएमआई',
    category: 'Esports',
    denomination: '₹20',
    teaser: 'A battle-royale showdown to claim victory one drop at a time.',
    description: 'A premier Battlegrounds Mobile India tournament — a battle-royale experience where players gear up and drop in for the ultimate showdown.',
    date: 'Not specified',
    venue: 'Not specified',
    format: 'Tournament',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹10,000',
    teamSize: 'Not specified',
    participationType: 'Not specified',
    eligibility: 'Not specified',
    registrationDeadline: 'Not specified',
    _note: 'Ambiguous — BGMI description explicitly says "at FALAK 2025", inconsistent with FALAK \\'26 branding.',
  },
  {
    id: 'valorant',
    title: 'Valorant',
    devanagari: 'वैलोरेंट',
    category: 'Esports',
    denomination: '₹25',
    teaser: '5v5 tactical squad battles for glory and prizes.',
    description: 'A Valorant tournament where squads strategize and battle in intense 5v5 matches for a shot at glory, open to both casual players and pros.',
    date: 'Not specified',
    venue: 'Not specified',
    format: '5v5',
    rulesLink: '#',
    placeholderImg: IMG.chaiwala,
    registrationFee: 'Not specified',
    prizePool: 'Up to ₹12,000',
    teamSize: '5 (5v5)',
    participationType: 'Team',
    eligibility: 'Open to casual players and pros alike',
    registrationDeadline: 'Not specified',
  },
];
