export interface SportsEvent {
  id: string;
  title: string;
  iconName: string;
  teaser: string;
  description: string;
  date: string;
  venue: string;
  format: string;
  rulesLink: string;
  img: string;
  height: number;
  registrationFee: string;
  prizePool: string;
  teamSize: string;
  participationType: string;
  eligibility: string;
  registrationDeadline: string;
  _note?: string; // Internal note for conflicts
}

export const sportsData: SportsEvent[] = [
  {
    id: 'football',
    title: 'FOOTBALL',
    iconName: 'Trophy',
    teaser: '11v11. Full contact. No excuses.',
    description: 'The premier tournament of Falak. 90 minutes of sheer endurance, tactical aggression, and clinical finishing. Bring your best XI.',
    date: '12th October – 17th October 2026',
    venue: 'Not specified',
    format: '11v11 Knockout',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-1.jpg',
    height: 400,
    registrationFee: 'Men: ₹8,500 per team; Women: ₹4,000 per team',
    prizePool: 'Men: 1st ₹50,000, 2nd ₹30,000; Women: 1st ₹20,000, 2nd ₹12,000; Category total: ₹1,12,000',
    teamSize: 'Men: max 18 players (11v11); Women: max 10 players (7v7)',
    participationType: 'Team',
    eligibility: 'Undergraduate students only; age not to exceed 25 years',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'basketball',
    title: 'BASKETBALL',
    iconName: 'Dribbble',
    teaser: 'Hardwood. High stakes. Fast breaks.',
    description: 'Full-court, high-octane 5v5. We want lockdown defense and ice-cold shooting. If you can\'t run the floor, don\'t step on the court.',
    date: '13th October – 17th October 2026',
    venue: 'Not specified',
    format: '5v5 Full Court',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-2.jpg',
    height: 550,
    registrationFee: 'Men: ₹5,000 per team; Women: ₹3,000 per team',
    prizePool: 'Men: 1st ₹30,000, 2nd ₹18,000; Women: 1st ₹20,000, 2nd ₹12,000; Category total: ₹80,000',
    teamSize: 'Max 12 players, min 6 players',
    participationType: 'Team',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'cricket',
    title: 'CRICKET',
    iconName: 'Flame',
    teaser: 'A white-ball league-to-knockout cricket tournament with escalating over-counts.',
    description: 'Teams field a full playing XI through a group/league stage of 12-over matches, with the knockout semi-finals and finals extended to 15 overs per innings.',
    date: '9th October – 15th October 2026',
    venue: 'Not specified',
    format: '11v11 Limited Overs',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-3.jpg',
    height: 450,
    registrationFee: '₹8,000 per team',
    prizePool: 'Winners: ₹40,000; Runners-up: ₹25,000; Category total: ₹65,000',
    teamSize: '11 playing XI; up to 5 substitutes',
    participationType: 'Team',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
    _note: 'Ambiguous — Only a Men\'s table is given. Requires verification if Women\'s was omitted. Changed slug from box-cricket to cricket to match master file.',
  },
  {
    id: 'badminton',
    title: 'BADMINTON',
    iconName: 'Zap',
    teaser: 'Lightning reflexes. Lethal smashes.',
    description: 'Test your reaction time on championship-grade synthetic courts. Singles and doubles brackets. No mercy on the drop shots.',
    date: '14th October – 17th October 2026',
    venue: 'Not specified',
    format: 'Singles & Doubles',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-6.jpg',
    height: 600,
    registrationFee: 'Men\'s Team: ₹3,500; Women\'s Team: ₹2,500; Mixed Doubles: ₹800',
    prizePool: 'Men\'s Team: 1st ₹10,000, 2nd ₹7,000; Women\'s Team: 1st ₹7,000, 2nd ₹4,000; Mixed Doubles: 1st ₹5,000, 2nd ₹3,000; Category total: ₹36,000',
    teamSize: 'Men\'s squad: 5–7 players; Women\'s squad: 3–5 players; Mixed Doubles: 2 players',
    participationType: 'Team (Men\'s/Women\'s); Pair (Mixed Doubles)',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'volleyball',
    title: 'VOLLEYBALL',
    iconName: 'Goal',
    teaser: 'Iron walls. Thunderous spikes.',
    description: 'Dominate above the net. 6v6 action requiring flawless communication and aggressive front-court play.',
    date: '14th October – 17th October 2026',
    venue: 'Not specified',
    format: '6v6 Best of 3',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-7.jpg',
    height: 400,
    registrationFee: 'Men: ₹3,400 per team; Women: ₹2,000 per team',
    prizePool: 'Men: 1st ₹10,000, 2nd ₹8,000; Women: 1st ₹8,000, 2nd ₹4,000; Category total: ₹30,000',
    teamSize: 'Max 12 players per team',
    participationType: 'Team',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'table-tennis',
    title: 'TABLE TENNIS',
    iconName: 'Crosshair',
    teaser: 'Spin. Speed. Survival.',
    description: 'Blistering rallies and split-second decisions. International standard tables. Individual and team knockouts for the sharpest reflexes on campus.',
    date: '14th October – 17th October 2026',
    venue: 'Not specified',
    format: 'Individual & Team',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-8.jpg',
    height: 500,
    registrationFee: 'Men\'s Team: ₹1,800; Women\'s Team: ₹1,500',
    prizePool: 'Men\'s Team: 1st ₹7,500, 2nd ₹4,500; Women\'s Team: 1st ₹5,000, 2nd ₹3,000; Category total: ₹20,000',
    teamSize: 'Men\'s: min 4, max 5 (1 substitute); Women\'s: min 3, max 5 (2 substitutes)',
    participationType: 'Team',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'athletics',
    title: 'ATHLETICS',
    iconName: 'Timer',
    teaser: 'A multi-event track meet spanning sprints, middle distance, and relays for men, women, and mixed teams.',
    description: 'A 3-day track meet covering 100M/200M/400M for both genders, 800M (women only), 1500M (men only), and a 4x100M relay open to men\'s, women\'s, and mixed teams.',
    date: '15th October – 17th October 2026',
    venue: 'Not specified',
    format: 'Individual & Relay',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-4.jpg',
    height: 450,
    registrationFee: 'Men\'s 100M: ₹400; All other individual events: ₹300',
    prizePool: 'Each individual event: total ₹5,800; Each 4x100M Relay category: total ₹13,000; Category grand total: ₹85,400',
    teamSize: 'Individual events: 1 athlete; 4x100M Relay: 4 athletes',
    participationType: 'Individual (track events); Team (relay)',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
    _note: 'Conflict — Registration fee: table says Men\'s 100M ₹450 / others ₹350; footnote says ₹400 / ₹300. Used footnote per instructions, verify with committee.',
  },
  {
    id: 'chess',
    title: 'CHESS',
    iconName: 'PuzzlePiece',
    teaser: 'A Swiss-system rapid chess team battle across four boards, every round.',
    description: 'Mixed teams of 4–6 players field four boards per round in a Swiss-system rapid format, with every team playing every round and no knockout stage.',
    date: '15th October – 17th October 2026',
    venue: 'Not specified',
    format: 'Swiss-system Rapid',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-5.jpg',
    height: 550,
    registrationFee: '₹1,800 per team',
    prizePool: '1st prize ₹6,000, 2nd prize ₹4,000 (Total: ₹10,000)',
    teamSize: '4–6 players',
    participationType: 'Team (Mixed)',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
    _note: 'Conflict — Prize pool: category summary says ₹20,000 total; event-detail page says ₹10,000. Used ₹10,000 per instructions, verify with committee.',
  },
  {
    id: 'lawn-tennis',
    title: 'LAWN TENNIS',
    iconName: 'TennisBall',
    teaser: 'Team tennis ties plus a brand-new individual women\'s singles event.',
    description: 'Men\'s teams contest best-of-3-rubber ties, while a newly introduced Women\'s Singles event runs the same extended-set league format head-to-head.',
    date: '14th October – 17th October 2026',
    venue: 'Not specified',
    format: 'Best of 3 Rubbers',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-9.jpg',
    height: 400,
    registrationFee: 'Men\'s Team: ₹3,000; Women\'s Singles: ₹400',
    prizePool: 'Men\'s Team: 1st ₹12,000, 2nd ₹7,000; Women\'s Singles: 1st ₹4,000, 2nd ₹2,000; Category total: ₹25,000',
    teamSize: 'Men\'s Team: min 2, max 4 players; Women\'s Singles: Individual',
    participationType: 'Team (Men\'s); Individual (Women\'s Singles)',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
  },
  {
    id: 'squash',
    title: 'SQUASH',
    iconName: 'Barbell',
    teaser: 'A knockout squash showdown decided by rally-point scoring to 11.',
    description: 'Men\'s and Women\'s Singles are contested as straight knockouts, with matches played best of 5 games to 11 points.',
    date: '15th October – 17th October 2026',
    venue: 'Not specified',
    format: 'Singles Knockout',
    rulesLink: '#',
    img: '/assets/reference/sports/ref-10.jpg',
    height: 500,
    registrationFee: 'Men\'s Singles: ₹500; Women\'s Singles: ₹400',
    prizePool: 'Men\'s Singles: 1st ₹3,000, 2nd ₹2,000; Women\'s Singles: 1st ₹2,500, 2nd ₹1,500; Category total: ₹9,000',
    teamSize: 'Individual',
    participationType: 'Individual',
    eligibility: 'Undergraduate students only; age ≤25',
    registrationDeadline: 'Not specified',
  }
];
